Running into build issues with Rust
Probably need to tweak environment variables, paths, etc.

```
     Running `rustc --crate-name libarchive3_sys /Users/build/.cargo/registry/src/github.com-1ecc6299db9ec823/libarchive3-sys-0.1.2/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C debuginfo=2 -C metadata=303d90d9046fb93c -C extra-filename=-303d90d9046fb93c --out-dir /hab/cache/src/hab-0.59.0/x86_64-apple-darwin/release/deps --target x86_64-apple-darwin -L dependency=/hab/cache/src/hab-0.59.0/x86_64-apple-darwin/release/deps -L dependency=/hab/cache/src/hab-0.59.0/release/deps --extern libc=/hab/cache/src/hab-0.59.0/x86_64-apple-darwin/release/deps/liblibc-4d133fb1d8b56708.rlib --cap-lints allow -L native=/usr/local/Cellar/hab-libarchive/3.2.0/lib -L native=/usr/local/opt/zlib/lib -L native=/usr/local/opt/xz/lib -L native=/usr/local/opt/bzip2/lib -L native=/usr/local/opt/expat/lib -L native=/usr/local/Cellar/hab-libiconv/1.14/lib -l static=archive -l static=z -l static=lzma -l static=bz2 -l static=expat -l static=iconv`
error: could not find native static library `archive`, perhaps an -L flag is missing?

error: aborting due to previous error

error: Could not compile `libarchive3-sys`.

Caused by:
  process didn't exit successfully: `rustc --crate-name libarchive3_sys /Users/build/.cargo/registry/src/github.com-1ecc6299db9ec823/libarchive3-sys-0.1.2/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C debuginfo=2 -C metadata=303d90d9046fb93c -C extra-filename=-303d90d9046fb93c --out-dir /hab/cache/src/hab-0.59.0/x86_64-apple-darwin/release/deps --target x86_64-apple-darwin -L dependency=/hab/cache/src/hab-0.59.0/x86_64-apple-darwin/release/deps -L dependency=/hab/cache/src/hab-0.59.0/release/deps --extern libc=/hab/cache/src/hab-0.59.0/x86_64-apple-darwin/release/deps/liblibc-4d133fb1d8b56708.rlib --cap-lints allow -L native=/usr/local/Cellar/hab-libarchive/3.2.0/lib -L native=/usr/local/opt/zlib/lib -L native=/usr/local/opt/xz/lib -L native=/usr/local/opt/bzip2/lib -L native=/usr/local/opt/expat/lib -L native=/usr/local/Cellar/hab-libiconv/1.14/lib -l static=archive -l static=z -l static=lzma -l static=bz2 -l static=expat -l static=iconv` (exit code: 101)
  ```

Signed-off-by: Christopher Maier <cmaier@chef.io>